
package org.countrycurrency.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Sat Nov 29 18:34:42 CET 2014
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "getAllCurrenciesResponse", namespace = "http://ws.countrycurrency.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllCurrenciesResponse", namespace = "http://ws.countrycurrency.org/")

public class GetAllCurrenciesResponse {

    @XmlElement(name = "currencies")
    private java.util.Set<org.countrycurrency.ws.type.Currency> currencies;

    public java.util.Set<org.countrycurrency.ws.type.Currency> getCurrencies() {
        return this.currencies;
    }

    public void setCurrencies(java.util.Set<org.countrycurrency.ws.type.Currency> newCurrencies)  {
        this.currencies = newCurrencies;
    }

}

