
package org.countrycurrency.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Sat Nov 29 18:34:42 CET 2014
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "getCurrencyByCountry", namespace = "http://ws.countrycurrency.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCurrencyByCountry", namespace = "http://ws.countrycurrency.org/", propOrder = {"validation", "country"})

public class GetCurrencyByCountry {

    @XmlElement(name = "validation")
    private org.countrycurrency.ws.type.Validation validation;
    @XmlElement(name = "country")
    private org.countrycurrency.ws.type.Country country;

    public org.countrycurrency.ws.type.Validation getValidation() {
        return this.validation;
    }

    public void setValidation(org.countrycurrency.ws.type.Validation newValidation)  {
        this.validation = newValidation;
    }

    public org.countrycurrency.ws.type.Country getCountry() {
        return this.country;
    }

    public void setCountry(org.countrycurrency.ws.type.Country newCountry)  {
        this.country = newCountry;
    }

}

